version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-bd:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "wipro11"
    ports:
      - "3307:3306"
    networks:
      - algafood-network

  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "algafood-bd:3307", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-bd
    ports:
      - "8080:8080"
    networks:
      - algafood-network
    depends_on:
      - algafood-bd